Qcm
WildCodeSchool/reims-0919-js-quizz pull request #4
Opened 2019-11-13 10:18 UTC by blemia51

2019-11-13 17:02 UTC, ghost requested changes

2019-11-13 17:02 UTC, ghost commented on quizz/src/components/ButtonBoolH.js
> +import React from "react"
If file is obsolete, remove it

2019-11-13 17:02 UTC, ghost commented on quizz/src/components/ButtonMask.js
> +
obsolete

2019-11-13 17:02 UTC, ghost commented on quizz/src/components/ButtonQcm.css
> +/* .button-order :nth-child(1) {
dead code

2019-11-13 17:02 UTC, ghost commented on quizz/src/components/ButtonQcm.js
> +        console.log(this.state.buttonWinOrder)
no more console.log at this state

2019-11-13 17:02 UTC, ghost commented on quizz/src/components/ButtonQcm.js
> +                // id='winButton'
dead code

2019-11-13 17:02 UTC, ghost commented on quizz/src/components/ButtonQcm.js
> +                onClick={event =>{this.setState({win: true});this.props.incrementScore();}}
Send this into a method (handleCorrectAnswer ?)

2019-11-13 17:02 UTC, ghost commented on quizz/src/components/ButtonQcm.js
> +            <button onClick={event =>this.setState({lost: true})}
function in onClick is used several times -> store it in a method so you don't repeat yourself (dry)

2019-11-13 17:02 UTC, ghost commented on quizz/src/components/ButtonQcm.js
> +             <div><button onClick={event =>{this.setState({win: false, lost :false});{this.props.getQuestions()};{this.buttonWinOrder()};{this.props.incrementQuestionNumber()}}}
Will change

2019-11-13 17:02 UTC, ghost commented on quizz/src/components/CardQuestion.js
> +        console.log(this.state.arrayQuestions)
no more console.log()

2019-11-13 17:02 UTC, ghost commented on quizz/src/components/CardQuestionBool.js
> +        console.log(this.state.arrayQuestions)
same thing with console.log

2019-11-13 17:02 UTC, ghost commented on quizz/src/components/CardQuestionBoolH.js
> +import React from "react"
Will be deleted

2019-11-13 17:02 UTC, ghost commented on quizz/src/components/ChoiceQuizz.js
> +import React from 'react'
will be deleted

2019-11-13 17:02 UTC, ghost commented on quizz/src/components/ChoixQfmVF.js
> +    constructor(props) {
don't keep useless constructor

2019-11-13 17:02 UTC, ghost commented on quizz/src/components/ChoixQfmVF.js
> +      console.log(this.props)
conosle.log()

2019-11-13 17:02 UTC, ghost commented on quizz/src/components/ListCategory.js
> +const category = [
set data in a separate file

2019-11-13 17:02 UTC, ghost commented on quizz/src/components/ListCategory.js
> +//     <ChoixQfmVF name={this.props.name} image={this.props.image} />
?

2019-11-13 17:02 UTC, ghost commented on quizz/src/components/LostMask.js
> +
will be deleted

2019-11-13 17:02 UTC, ghost commented on quizz/src/components/Maskbutton.js
> +
Will be deleted

2019-11-13 17:02 UTC, Sheoo commented on quizz/src/components/WinButtonPos..js
> +function RandomButton(max) {
will be deleted

2019-11-13 17:02 UTC, Sheoo commented on quizz/src/components/WinMask.js
> +
will be deleted

2019-11-13 17:02 UTC, Sheoo commented on quizz/src/components/maskbutton.js
> +
will be deleted

2019-11-14 09:12 UTC, blemia51 commented on quizz/src/components/ButtonBoolH.js
> +import React from "react"
done

2019-11-14 09:12 UTC, blemia51 commented on quizz/src/components/ButtonMask.js
> +
done

2019-11-14 09:12 UTC, blemia51 commented on quizz/src/components/ButtonQcm.css
> +/* .button-order :nth-child(1) {
done

2019-11-14 09:13 UTC, blemia51 commented on quizz/src/components/ButtonQcm.js
> +        console.log(this.state.buttonWinOrder)
ok

2019-11-14 09:15 UTC, blemia51 commented on quizz/src/components/ButtonQcm.js
> +                // id='winButton'
done

2019-11-14 09:15 UTC, blemia51 commented on quizz/src/components/LostMask.js
> +
done

2019-11-14 09:15 UTC, blemia51 commented on quizz/src/components/Maskbutton.js
> +
done

2019-11-14 09:16 UTC, blemia51 commented on quizz/src/components/WinButtonPos..js
> +function RandomButton(max) {
done

2019-11-14 09:16 UTC, blemia51 commented on quizz/src/components/WinMask.js
> +
done

2019-11-14 09:16 UTC, blemia51 commented on quizz/src/components/maskbutton.js
> +
done

2019-11-14 09:28 UTC, ghost approved these changes

2019-11-14 09:29 UTC, merged